org: secondstate
app: ternsorflow-faas
stage: prod

component: layer
name: tf-layer

inputs:
  region: ${env:region}
  src:
    bucket: ${output:${stage}:${app}:tf-cos.bucket}
    object: layer.zip
  runtimes:
    - CustomRuntime
